var cityArray = [
  "London, England",
  "Paris, France",
  "New York, US",
  "Tokyo, Japan",
  "Barcelona, Spain",
  "Moscow, Russia",
  "Chicago, US",
  "Singapore",
  "Dubai, United Arab States",
  "San Francisco, US",
  "Madrid, Spain",
  "Amsterdam, The Netherlands",
  "Los Angeles, US",
  "Rome, Italy",
  "Boston, USA",
  "San José, US",
  "Toronto, Canada",
  "Washington, US",
  "Zurich, Switzerland",
  "Hong Kong, China",
  "Beijing, China",
  "Berlin, Germany",
  "Sydney, Australia",
  "Las Vegas, US",
  "Frankfurt, Germany",
  "Miami, US",
  "San Diego, US",
  "Seoul, South Korea",
  "Prague, Czechia",
  "Munich, Germany",
  "Houston, US",
  "Milan, Italy",
  "Dublin, Ireland",
  "Seattle, USA",
  "Dallas, US",
  "Istanbul, Turkey",
  "Vancouver, Canada",
  "Melbourne, Australia",
  "Vienna, Austria",
  "Abu Dhabi, United Arab States",
  "Calgary, Canada",
  "Brussels, Belgium",
  "Denver, US",
  "Doha, Qatar",
  "Oslo, Norway",
  "Orlando, US",
  "Austin, US",
  "Stockholm, Sweden",
  "Montreal, Canada",
  "Philadelphia, US",
  "Brisbane, Australia",
  "Atlanta, US",
  "Copenhagen, Denmark",
  "St. Petersburg, Russia",
  "Perth, Australia",
  "Minneapolis, US",
  "Lisbon, Portugal",
  "Venice, Italy",
  "Portland, US",
  "Hamburg, Germany",
  "Tel Aviv, Israel",
  "Lyon, France",
  "Florence, Italy",
  "Stuttgart, Germany",
  "Luxembourg, Luxembourg",
  "Edmonton, US",
  "Osaka, Japan",
  "Auckland, New Zealand",
  "Ottawa, Canada",
  "Budapest, Hungary",
  "Helsinki, Finland",
  "Athens, Greece",
  "Cologne, Germany",
  "Bangkok, Thailand",
  "Charlotte, US",
  "Phoenix, US",
  "New Orleans, US",
  "Baltimore, US",
  "Valencia, Spain",
  "Manchester, England",
  "Liverpool, England",
  "Szczecin, Poland",
  "Nashville, US",
  "Düsseldorf, Germany",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Warsaw, Poland",
  "Marseille, France",
  "Birmingham, England",
  "Shanghai, China"
];

function newCity() {
  var randomNumber = Math.floor(Math.random() * cityArray.length);
  document.getElementById("textField").innerHTML = cityArray[randomNumber];
}
